using _Project.Dialogue;
using _Project.Dialogue.Config;
using _Project.Dialogue.Lines;
using _Project.Tests.EditMode.Mocks;
using NUnit.Framework;

namespace _Project.Tests.EditMode
{
    public class OptionsDialogueLineTests
    {
        [Test]
        public void OptionsDialogueLineCanLookUpOptionByUniqueId()
        {
            DialogueRunner runner = DialogueRunnerMocks.GetSimpleOption(null, 0);
            OptionsDialogueLine line = (OptionsDialogueLine) runner.CurrentDialogueLine;

            SpokenDialogueLine option1 = line.GetOptionByNext("next-option-branch-1");
            Assert.AreEqual("speaker-1", option1.Speaker);
            Assert.AreEqual("Test line - option - branch 1", option1.Dialogue);
            Assert.AreEqual("next-option-branch-1", option1.Next);

            SpokenDialogueLine option2 = line.GetOptionByNext("next-option-branch-2");
            Assert.AreEqual("speaker-2", option2.Speaker);
            Assert.AreEqual("Test line - option - branch 2", option2.Dialogue);
            Assert.AreEqual("next-option-branch-2", option2.Next);
        }

        [Test]
        public void OptionsDialogueLineCanTraverseInlineBranches()
        {
            DialogueAssetLoader loader = new DialogueAssetLoader("OptionsDialogueLineTest/");
            DialogueRunner runner = new DialogueRunner(loader.Records);

            runner.SetCurrentRecord("branching-options");
            Assert.True(runner.Records.ContainsKey("branching-options-option-branch-1-autogenerated"));
            Assert.True(runner.Records.ContainsKey("branching-options-option-branch-2-autogenerated"));

            OptionsDialogueLine optionsDialogueLine = (OptionsDialogueLine) runner.CurrentDialogueLine;

            SpokenDialogueLine option1 = optionsDialogueLine.Options[0];

            runner.StepToNextDialogueLine(option1);
            SpokenDialogueLine line1 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line1.Speaker);
            Assert.AreEqual("Branch 1 line 1", line1.Dialogue);

            runner.StepToNextDialogueLine();
            SpokenDialogueLine line2 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line2.Speaker);
            Assert.AreEqual("Branch 1 line 2", line2.Dialogue);

            runner.StepToNextDialogueLine();
            SpokenDialogueLine line3 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line3.Speaker);
            Assert.AreEqual("Branch 1 line 3", line3.Dialogue);
            Assert.AreEqual("branching-options", line3.Next);

            // Testing that Step() at the end of a branch picks up as normal
            runner.StepToNextDialogueLine();
            OptionsDialogueLine line4 = (OptionsDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line4.Speaker);
            Assert.AreEqual("This is an options test", line4.Dialogue);
            Assert.IsInstanceOf<OptionBranchDialogueLine>(line4.Options[0]);
            Assert.IsInstanceOf<OptionBranchDialogueLine>(line4.Options[1]);
        }

        [Test]
        public void OptionsDialogueLineCanTraverseNestedInlineBranches()
        {
            DialogueAssetLoader loader = new DialogueAssetLoader("OptionsDialogueLineTest/");
            DialogueRunner runner = new DialogueRunner(loader.Records);

            runner.SetCurrentRecord("nested-branching-options");
            Assert.True(runner.Records.ContainsKey("nested-branching-options-option-branch-1-autogenerated"));
            Assert.True(runner.Records.ContainsKey("nested-branching-options-option-branch-2-autogenerated"));
            Assert.True(runner.Records.ContainsKey("nested-branching-options-option-branch-3-autogenerated"));
            Assert.True(runner.Records.ContainsKey("nested-branching-options-option-branch-4-autogenerated"));

            OptionsDialogueLine optionsDialogueLine = (OptionsDialogueLine) runner.CurrentDialogueLine;

            SpokenDialogueLine option1 = optionsDialogueLine.Options[0];

            runner.StepToNextDialogueLine(option1);
            SpokenDialogueLine line1 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line1.Speaker);
            Assert.AreEqual("Branch 1 line 1", line1.Dialogue);

            runner.StepToNextDialogueLine();
            SpokenDialogueLine line2 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line2.Speaker);
            Assert.AreEqual("Branch 1 line 2", line2.Dialogue);

            // Nested option line
            runner.StepToNextDialogueLine();
            SpokenDialogueLine line3 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line3.Speaker);
            Assert.AreEqual("Branch 1 line 3", line3.Dialogue);

            // 1.1
            OptionsDialogueLine nestedOptionsDialogueLine = (OptionsDialogueLine) runner.CurrentDialogueLine;
            SpokenDialogueLine option11 = nestedOptionsDialogueLine.Options[0];

            runner.StepToNextDialogueLine(option11);
            SpokenDialogueLine line11 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line11.Speaker);
            Assert.AreEqual("Branch 1.1 line 1", line11.Dialogue);

            runner.StepToNextDialogueLine();
            SpokenDialogueLine line12 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line12.Speaker);
            Assert.AreEqual("Branch 1.1 line 2", line12.Dialogue);

            runner.StepToNextDialogueLine();
            SpokenDialogueLine line13 = (SpokenDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line13.Speaker);
            Assert.AreEqual("Branch 1.1 line 3", line13.Dialogue);

            // Testing that Step() at the end of a branch picks up as normal
            runner.StepToNextDialogueLine();
            OptionsDialogueLine line4 = (OptionsDialogueLine) runner.CurrentDialogueLine;
            Assert.AreEqual("options-test-user", line4.Speaker);
            Assert.AreEqual("This is an options test", line4.Dialogue);
            Assert.IsInstanceOf<OptionBranchDialogueLine>(line4.Options[0]);
            Assert.IsInstanceOf<OptionBranchDialogueLine>(line4.Options[1]);
        }
    }
}