using _Project.Dialogue.Config;

namespace _Project.Dialogue.Lines
{
    /// <summary>
    /// A DialogueLine is a single entry in a DialogueRecord (which is a subset of a larger conversation/narration)
    /// <para>
    /// This is the base class of this system, all classes need to be based off of this
    /// </para>
    /// </summary>
    public abstract class DialogueLine {

        // TODO: ID?

        /// <summary>
        /// ID of the next line of dialogue
        /// <para>
        /// If not specified, this will be autogenerated?
        /// </para>
        /// </summary>
        public string Next;

        public DialogueLine(DialogueLineConfig config)
        {
            Next = config.next;
        }
    }
}