using System.Collections.Generic;
using _Project.Dialogue.Config;

namespace _Project.Dialogue.Lines
{
    /// <summary>
    /// A DialogueLine is a single entry in a DialogueRecord (which is a subset of a larger conversation/narration)
    /// </summary>
    public class DialogueLine : IDialogueLine {
        public string speaker;

        /// <summary>
        /// Dialogue of the line, what is being said
        /// </summary>
        public string dialogue;

        /// <summary>
        /// ID of the next line of dialogue
        /// <para>
        /// If not specified, this will be autogenerated?
        /// </para>
        /// </summary>
        public string next;

        /// <summary>
        /// Optional list of DialogueLine records
        /// <para>
        /// TODO: Remove "object composition cycle in one or more of your serialized classes" by changing type
        /// </para>
        /// </summary>
        public List<DialogueLine> options;

        /// <summary>
        /// String of a pre-defined Action to be fired
        /// </summary>
        public string command;

        public DialogueLine(DialogueLineConfig config)
        {
            speaker = config.speaker;
            dialogue = config.dialogue;
            next = config.next;
        }
    }
}