using System.Collections.Generic;
using _Project.Dialogue.Config;

namespace _Project.Dialogue.Lines
{
    /// <summary>
    /// A DialogueLine is a single entry in a DialogueRecord (which is a subset of a larger conversation/narration)
    /// </summary>
    public class DialogueLine : IDialogueLine {

        /// <summary>
        /// Who is speaking this line?
        /// </summary>
        public string Speaker;

        /// <summary>
        /// Dialogue of the line, what is being said
        /// </summary>
        public string Dialogue;

        /// <summary>
        /// ID of the next line of dialogue
        /// <para>
        /// If not specified, this will be autogenerated?
        /// </para>
        /// </summary>
        public string Next;

        public DialogueLine(DialogueLineConfig config)
        {
            Speaker = config.speaker;
            Dialogue = config.dialogue;
            Next = config.next;
        }
    }
}