using System.Collections.Generic;

namespace _Project.Dialogue
{
    /// <summary>
    /// A DialogueLine is a single entry in a DialogueRecord (which is a subset of a larger conversation/narration)
    /// </summary>
    [System.Serializable]
    public class DialogueLine {
        /// <summary>
        /// Who is saying this dialogue?
        /// <para>
        /// TODO: Injectable enum for characters?
        /// </para>
        /// </summary>
        public string speaker;

        /// <summary>
        /// Dialogue of the line, what is being said
        /// </summary>
        public string dialogue;

        /// <summary>
        /// ID of the next line of dialogue
        /// <para>
        /// If not specified, this will be autogenerated
        /// </para>
        /// </summary>
        public string next;

        /// <summary>
        /// Optional list of DialogueLine records
        /// <para>
        /// TODO: Remove "object composition cycle in one or more of your serialized classes" by changing type
        /// </para>
        /// </summary>
        public List<DialogueLine> options;

        /// <summary>
        /// String of a pre-defined Action to be fired
        /// </summary>
        public string command;
    }
}