using System.Collections.Generic;

namespace _Project.Dialogue
{
    /// <summary>
    /// A DialogueLine is a single entry in a DialogueRecord (which is a subset of a larger conversation/narration)
    /// </summary>
    [System.Serializable]
    public class DialogueLine {
        // TODO: Comment and markup after readding "meta"
        /// <summary>
        /// Who is saying this dialogue?
        /// <para>
        /// TODO: Injectable enum for characters?
        /// </para>
        /// </summary>
        public string Speaker;

        /// <summary>
        /// Dialogue of the line, what is being said
        /// </summary>
        public string Dialogue;

        /// <summary>
        /// ID of the next line of dialogue
        /// <para>
        /// If not specified, this will be autogenerated
        /// </para>
        /// </summary>
        public string Next;

        /// <summary>
        /// Optional list of DialogueLine records
        /// </summary>
        public List<DialogueLine> Options;
    }
}